### ISSUE TITLE
Cell toolbar option hide code does nothing, </> button works perfectly

### ISSUE THREAD

**Issue by itcarroll** [kirbs-/hide_code#12]
I just installed hide_code with pip3 and ran hide_code.hide_code.install() after creating an empty ~/.jupyter/custom/custom.js. The new </> button works as adversied, and is awesome. The individual cell toolbar option to hide code does nothing. I get a bunch of these errors in the javascript console:

```
Error in cell toolbar callback hide_code.hideCode TypeError: Cannot read property 'classname' of undefined
    at toggleHideCode (http://localhost:8888/custom/hide_code.js:48:31)
    at hideCodeGetter (http://localhost:8888/custom/hide_code.js:28:3)
    at http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:15212:34
    at CellToolbar.rebuild (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:15146:17)
    at Function.CellToolbar.rebuild_all (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:15114:39)
    at Function.CellToolbar.activate_preset (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:15098:25)
    at HTMLSelectElement.<anonymous> (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:27242:45)
    at HTMLSelectElement.x.event.dispatch (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:90:10006)
    at HTMLSelectElement.y.handle (http://localhost:8888/static/notebook/js/main.min.js?v=40e10638fcf65fc1c057bff31d165e9d:90:6789)
```

I know nothing about javascript, but I can try going deeper if you need.

jupyter 4.0.6
ipython 4.0.0
Python 3.5.1

**Comment by kirbs-** [comment]
@itcarroll would you download the dev branch and try it out?

**Comment by itcarroll** [comment]
Works!
