### ISSUE TITLE
hide_code_latex doesn't work

### ISSUE THREAD

**Issue by jojomale** [kirbs-/hide_code#49]
Hey, I love your code hiding tool. I works great in the Browser and I can also produce pdfs from the command line. But I would really like to have the tex-file as well. I used
jupyter nbconvert --to hide_code_latex notebook.ipynb 
and
jupyter nbconvert --to hide_code_latexpdf notebook.ipynb
but this only spits out the following:
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/johanna/.local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/johanna/.local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/johanna/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/home/johanna/.local/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 446, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/home/johanna/.local/lib/python2.7/site-packages/nbconvert/exporters/export.py", line 188, in get_exporter
    return entrypoints.get_single('nbconvert.exporters', name).load()
  File "/home/johanna/.local/lib/python2.7/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named HideCodeLatexPDFExporter

I'd really appreciate some help.

**Comment by kirbs-** [comment]
This is a bug. I'll get this fixed shortly.

**Comment by waio1990** [comment]
Any update on this?

**Comment by kirbs-** [comment]
Fixed in version 0.5.1.
