### ISSUE TITLE
Export issue (jinja2.exceptions.TemplateNotFound: hide_code_full.tpl)

### ISSUE THREAD

**Issue by boundino** [kirbs-/hide_code#92]
Hi Chris,
Many thanks for developing this very helpful tool! 
I had some issues when trying to export to html. Below is the printout from `jupyter nbconvert --to hide_code_html mynote.ipynb`:

```
[NbConvertApp] Converting notebook mynote.ipynb to hide_code_html
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 387, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 148, in template
    self._template_cached = self._load_template()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 358, in _load_template
    return self.environment.get_template(template_file)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 429, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: hide_code_full.tpl
```

Using the button in Jupyter notebook leads to the same error. I installed hide_code via pip install hide_code, so I suppose it's a clean installation.
Any help would be appreciated!

**Comment by kirbs-** [comment]
Would you post which version of nbconvert and hide_code you're using?

**Comment by boundino** [comment]
Thanks for the prompt reply!
I'm using nbconvert 6.0.6 and hide_code 0.5.5.

**Comment by kirbs-** [comment]
It looks like hide_code isn't fully installed. Can you run `jupyter nbextension list` and 'jupyter serverextension list` then post the output of each?

**Comment by kirbs-** [comment]
Also might be an issue with nbconvert 6.x. This was release a couple of weeks ago and I haven't tested hide_code against it yet.

**Comment by boundino** [comment]
Yes, please find the output below
```
xjjgww:~ xjjgwws-MacBook-Air:~
() xjjgww/ ⁄(⁄⁄•⁄ω⁄•⁄⁄)⁄$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/xjjgww/.jupyter/nbconfig
    notebook section
      hide_code/hide_code  enabled
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
xjjgww:~ xjjgwws-MacBook-Air:~
() xjjgww/ ⁄(⁄⁄•⁄ω⁄•⁄⁄)⁄$ jupyter serverextension list
config dir: /Users/xjjgww/.jupyter
    hide_code  enabled
    - Validating...
      hide_code  OK
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.8 OK
```

**Comment by kirbs-** [comment]
Just noticed [nbconvert 6.X](https://nbconvert.readthedocs.io/en/latest/changelog.html) may have broke this extension.

>template_path has become template_paths. If referring to a 5.x style .tpl template use the full path with the template_file argument to the file. On the command line the pattern is --template-file=<path/to/file.tpl>.

Try downgrading to nbconvert 5.x until I can get hide_code updated.

**Comment by boundino** [comment]
Many thanks for figuring this out!
I tried nbconvert 5.5 and 5.6 (uninstall 6.x and install 5.x). `jupyter nbconvert --to html` works but `jupyter nbconvert --to hide_code_html` threw
```
traitlets.traitlets.TraitError: 'template_path' is not a trait of 'HideCodeHTMLExporter' instances
``` 
The detailed output is as
```
[NbConvertApp] Converting notebook LIGOtutorialJLab.ipynb to hide_code_html
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'template_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 94, in from_notebook_node
    self.register_filter('highlight_code', highlight_code)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 383, in register_filter
    return self._register_filter(self.environment, name, jinja_filter)
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 126, in environment
    self._environment_cached = self._create_environment()
  File "/usr/local/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 411, in _create_environment
    additional_paths + \
  File "/usr/local/lib/python3.7/site-packages/hide_code/hide_code_html_exporter.py", line 27, in template_path
    return super(HideCodeHTMLExporter, self).template_path + [os.path.join(os.path.dirname(__file__), "Templates")]
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 575, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 538, in get
    default = obj.trait_defaults(self.name)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 1574, in trait_defaults
    "instances" % (n, type(self).__name__))
traitlets.traitlets.TraitError: 'template_path' is not a trait of 'HideCodeHTMLExporter' instances
```
Any idea why this happened? Thank you!

**Comment by kirbs-** [comment]
After some more digging nbconvert 6.0 also forces traitlets to upgrade from 4.x to 5.x. Would you try also downgrading to traitlets==4.3.3. This worked for me on a fresh virtualenv with Python 3.8.

Here's the output of `jupyter --version`
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.7
ipython          : 7.18.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : not installed
nbconvert        : 5.4.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```
